### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by valeriechen** [dongido001/pusher-chat-sentiment-analysis#10]
I'm getting this error:

Proxy error: Could not proxy request /api/login from localhost:8080 to http://127.0.0.1:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Even after I replaced localhost with 127.0.0.1. Do you have other suggestions?

**Comment by dongido001** [comment]
Is the [Flask app](https://github.com/dongido001/pusher-chat-sentiment-analysis/tree/master/api) running? - it should be running on http://localhost:5000 

And the [Vue app](https://github.com/dongido001/pusher-chat-sentiment-analysis) should be running on http://localhost:8080

So basically you should have two terminals running

**Comment by valeriechen** [comment]
Got it. How would this app be deployed if two terminals have to be running? (i.e. on heroku)

Thank you for your help!

**Comment by dongido001** [comment]
Anybody wanting to deploy both apps to a single instance should refer to my comment on #11, please
