### ISSUE TITLE
What service would I use if I want to deploy both on one server? And need to resolve database issues

### ISSUE THREAD

**Issue by tycooperaow** [dongido001/pusher-chat-sentiment-analysis#11]
I have taken this application, and altered it into something significantly different and now I'm seeking to deploy this app. Currently I have the frontend (which would be **localhost:8080**) running on **firebase**, and I have the backend (which would've been **localhost:5000**) on **pythonanywhere**? Anywhere where I could use one service and have them both deployed? 

Also when I try to _get_ or _post_ data to the database I receive this error on my backend:

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users [SQL: 'SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password \nFROM users \nWHERE users.username = ?\n LIMIT ? OFFSET ?'] [parameters: ('jama juice', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)`

Anyway I can resolve this database issue? I have everything set up correctly.

**Comment by dongido001** [comment]
1. If you want to deploy both on a single instance,  you can deploy it to servers like DigitalOcean or Heroku but then you need to do some modification to the flask app so that it renders the Front-end code - You can see example code on how this is done on this [project](https://github.com/dongido001/flask-vue-example)

2. Did you run the command to create the [database](https://pusher.com/tutorials/chat-flask-vue-part-2)?:

```    
    # Go to the Flask app
    $ cd api

    # Activate your virtualenv

    # Enter python interactive shell
    $ python
    >>> from database import init_db
    >>> init_db()
```

**Comment by tycooperaow** [comment]
yes I ran that command tot run the database, but I have still experienced the same issue. 

Here is the code : 
_#database.py_
```

from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine('sqlite:///database.db', convert_unicode=True, pool_pre_ping=True)
db_session = scoped_session(sessionmaker(autocommit=False,
                                            autoflush=False,
                                            bind=engine))

Base = declarative_base()
Base.query = db_session.query_property()

def init_db():
    import models
    Base.metadata.create_all(bind=engine)

```
_models.py_
```
from sqlalchemy import Column, Integer, String, Text, ForeignKey
from database import Base


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(50), unique=True)
    password = Column(String(128)) # add nullible = False

    def __init__(self, username=None, password=None):
        self.username = username
        self.password = password

    def __repr__(self):
        return '<User %r>' % (self.username)


class Channel(Base):
    __tablename__ = 'channels'
    id = Column(Integer, primary_key=True)
    name = Column(String(60))
    from_user = Column(Integer, ForeignKey('users.id'))
    to_user = Column(Integer, ForeignKey('users.id'))


class Message(Base):
    __tablename__ = 'messages'
    id = Column(Integer, primary_key=True)
    message = Column(Text)
    from_user = Column(Integer, ForeignKey('users.id'))
    to_user = Column(Integer, ForeignKey('users.id'))
    channel_id = Column(Integer, ForeignKey('channels.id'))
```

**Comment by dongido001** [comment]
I see. Everything seems good, not sure why the error is showing up. Try deleting the database.**db** file and try running the command again.

We can do a quick TeamView if the error persists. You can ping me via email.

**Comment by tycooperaow** [comment]
We can do that, how do we go about creating that?

**Comment by dongido001** [comment]
With this [app](https://www.teamviewer.com/), you can share your screen with me -

**Comment by dongido001** [comment]
Is the error on the server or on your local?

**Comment by tycooperaow** [comment]
it's on the server

**Comment by tycooperaow** [comment]
I'm getting team view now

**Comment by dongido001** [comment]
Oh ok. Not sure if I can help with that since I have no experience with Pythonanywhere but we can still give it a try!

**Comment by tycooperaow** [comment]
Okay, thank you

**Comment by tycooperaow** [comment]
how do Invite you?

**Comment by dongido001** [comment]
I need to give me your TeamViewer ID and Pass

**Comment by tycooperaow** [comment]
how do I send that privately?
Do I email it to you?

**Comment by dongido001** [comment]
Yeah, email

**Comment by tycooperaow** [comment]
sent!

**Comment by dongido001** [comment]
RECAP - for anyone facing the same issue: It was an issue due to the file location of the database.db file. We had to use the Direct path to the DB for it to work.

**Comment by tycooperaow** [comment]
And also make sure you set your secret and jwt keys as well!

**Comment by tycooperaow** [comment]
The link for running both flask and vue on the same instance didn't work

**Comment by dongido001** [comment]
@tycooperaow updated
