### ISSUE TITLE
I'm interested in testing and modifying this project a bit..but it seems severely outdated

### ISSUE THREAD

**Issue by XEVMERSHALL** [dongido001/pusher-chat-sentiment-analysis#20]
It's a very cool concept and I'm interested in playing around with it a bit, but so far I've been running into many issues some of which i'm not sure if it was just a me thing or something with the project itself. Some are with outdated modules.

For example the later versions of python don't have the clock attribute under time.

I seem to have fixed that particular issue, but now even after creating the registration and getting a message from postman that the user was successfully created I still get login failed error.

Please update, or help me navigate these errors. I'm mainly interested in adding a user registration option to the main interface rather than requiring to do it via postman.

**Comment by XEVMERSHALL** [comment]
Nevermind I figured out how to get it running, but I'd still like to know how I could add some registeration option right in the interface.

**Comment by dongido001** [comment]
funny only when you closed the issue that i got the notification of your comments. sorry!

**Comment by XEVMERSHALL** [comment]
Didn't know about that, I was actually interested in creating something similar for a Uni project, since then I've moved to something else.

It's all good.
