### ISSUE TITLE
Content not visible for App.vue component

### ISSUE THREAD

**Issue by stephendwolff** [dongido001/pusher-chat-sentiment-analysis#9]
The 2nd part of the tutorial:
 - https://pusher.com/tutorials/chat-flask-vue-part-2

is missing content at the end in an LI tag. Possibly because it has a Vue template? and isn't surrounded by {% verbatim %}?

**Comment by dongido001** [comment]
Hi @stephendwolff, 

Thanks for the heads up. I will check on it.

**Comment by dongido001** [comment]
It's fixed now! @stephendwolff 

Thanks again...
